trigger:  none
pool:  project01-pool
steps:
- task: TerraformTask@5
  displayName: Terraform-init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/prod'
    backendAzureRmUseEntraIdForAuthentication: false
    backendServiceArm: 'project01-sp'
    backendAzureRmResourceGroupName: 'vivek-storage-account-rg'
    backendAzureRmStorageAccountName: 'storage285001'
    backendAzureRmContainerName: 'container1'
    backendAzureRmKey: 'vivek.tfstate02'
- task: TerraformTask@5
  displayName: Terraform-validate
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/prod'
- task: TerraformTask@5
  displayName: Terraform-fmt
  inputs:
    provider: 'azurerm'
    command: 'custom'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/prod'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'project01-sp'
- task: TerraformTask@5
  displayName: Terraform-plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/prod'
    environmentServiceNameAzureRM: 'project01-sp'
- task: TerraformTask@5
  displayName: Terraform-apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/prod'
    environmentServiceNameAzureRM: 'project01-sp'